### ISSUE TITLE
WebApp-Profile: Som användare vill jag kunna ändra personliga uppgifter.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#63]
Tasks:
- [ ] WebApp-Profile: Skapa formulär som kopplas till en ViewModel för användarens uppgifter för namn, profilbild, email, lösenord, ålder samt kön (?). Validering med DataAnnotations samt Javascript.
- [ ] WebApp-Profile: Implementera funktion i en AccountController för att hämta nuvarande uppgifter via user API:et. 
- [ ] WebApp-Profile: Implementera funktion i en AccountController för att uppdatera uppgifter via user API:et. 

**Definition of done:**
- [ ] Personlig information ändras i databasen efter att jag som användare uppdaterar information i tillgängliga formulär och trycker på spara.
- [ ] Profilbilden går att byta ut via filuppladdning och ta bort om så önskas. Om ingen profilbild är uppladdad visas istället en generisk avatar bild.
- [ ] Personlig information som inte är tvingande kan uppdateras till att vara ett tomt fält.
- [ ] Vid lyckad uppdatering visas ett statusmeddelande som indikerar detta.
- [ ] Vid misslyckad uppdatering visasa ett felmeddelande som indikerar detta.

**Comment by DennisMikaj** [comment]
Testfall: Ändra personliga uppgifter på profilsidan

Användarberättelse: WebApp-Profile: Som användare vill jag kunna ändra personliga uppgifter. #63

    Syfte: Verifiera att användaren kan redigera och spara sina personliga uppgifter på profilsidan.

    Förutsättningar:
        Användaren är inloggad och har tillgång till profilsidan. Fälten för namn, ålder och e-post är hämtat från API och är förifyllt.

    Teststeg:
        Navigera till profilsidan.
        Ändra värdena i fälten för namn, e-post och telefonnummer.
        Klicka på "Spara ändringar".
        Logga ut och logga in igen för att kontrollera att ändringarna sparats korrekt.

    Förväntat resultat:
        De nya personliga uppgifterna visas på profilsidan efter sparning. 
        Uppgifterna är oförändrade även efter utloggning och inloggning.
        Ett meddelande visas som bekräftar att ändringarna har sparats (exempelvis "Dina uppgifter har uppdaterats").
        Felmeddelanden visas om ogiltiga inmatningar görs (t.ex. fel format på e-post eller tomt fält).

    Utfallsstatus: Pass / Fail
