### ISSUE TITLE
WebApp-Profile: Som användare vill jag kunna läsa RIKAs FAQ.

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#69]
-  [ ] WebApp-Profile-task: Skapa en  FAQ-modell som innehåller fält som` Id, Question, Answer, Category`.
- [ ]  WebApp-Profile-task: Skapa (`FAQService`) för att hämta och hantera FAQ-innehåll från databasen
- [ ] WebApp-Profile-task: Skapa (`FAQController`) för att hantera förfrågningar till FAQ-sidan med en metod för att ladda alla FAQ
eller FAQ per kategori.
- [ ] WebApp-Profile-task: Skapa `(FAQViewModel`) som ska skickas från kontrollern till vyn
- [ ] WebApp-Profile-task Skapa FAQ-vy i frontend med lista över vanliga frågor och svar samt kategorifiltrering.

Definition of done:
- [ ] FAQ-sidan är tillgänglig för alla användare, både inloggade och icke-inloggade
- [ ] FAQ-frågor och svar visas korrekt på sidan, antingen som en komplett lista eller filtrerat baserat på kategori.
- [ ] Möjlighet att uppdatera FAQ-frågor och svar via en adminpanel.

**Comment by Eleonor83** [comment]
Testfall: FAQ-funktionalitet

Användarberättelse: WebApp-Profile: Som användare vill jag kunna läsa RIKAs FAQ och definiera potentiella frågor, så att jag kan få svar på mina frågor effektivt.

Syfte: Att verifiera att FAQ-sidan är tillgänglig, att användare kan se och filtrera FAQ-frågor samt att admin kan uppdatera innehållet.

Förutsättningar:
Användaren är antingen inloggad eller icke-inloggad. Det finns FAQ-innehåll i databasen. Adminanvändaren är inloggad för att uppdatera FAQ-frågor.

Teststeg:

Navigera till FAQ-sidan.
Kontrollera att sidan laddas utan fel och att alla FAQ-frågor och svar visas korrekt.
Filtrera FAQ-frågorna efter kategori och verifiera att endast relevanta frågor visas.
Om du är admin, navigera till adminpanelen, uppdatera en FAQ-fråga eller svar, spara ändringarna, och kontrollera att de reflekteras korrekt på FAQ-sidan.

Fel scenario:
Om det finns saknade eller felaktiga frågor/svar.
Filtreringen inte fungerar.
Ändringar av admin inte syns.

Utfallsstatus: Pass / Fail
