### ISSUE TITLE
WebApp-Profile: Implementera gränssnitt

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/WebApp-RIKA-WIN23#83]

**Comment by DennisMikaj** [comment]
Användarberättelse: WebApp-Profile: Implementera gränssnitt #83

    Syfte: Verifiera att användargränssnittet för profilsidan är korrekt implementerat enligt design- och funktionsspecifikationerna. Kontrollera att alla element och funktioner är placerade och fungerar enligt designen.

    Förutsättningar:
        Gränssnittet för profilsidan har implementerats.
        Användaren är inloggad och kan navigera till profilsidan.
        Designskiss eller prototyp finns tillgänglig för referens.

    Teststeg:
        Navigera till profilsidan från huvudmenyn.
        Verifiera att alla nödvändiga gränssnittselement finns på plats, inklusive:
            Profilbild
            Användarnamn och e-postadress
            Sektioner för redigering av personliga uppgifter, betalningsmetoder och leveransadress
            Ikoner eller knappar för navigering (exempelvis "Redigera", "Lägg till ny", "Spara", etc.)
            Sektioner för orderhistorik och önskelista
        Jämför layouten med designprototypen för att säkerställa att placering, färger, ikoner, och typsnitt matchar designen.
        Testa att klicka på knappar och länkar för att säkerställa att de fungerar och navigerar som förväntat.
        Kontrollera att sidan är responsiv och ser korrekt ut på olika enheter (exempelvis dator, surfplatta och mobil).
        Bekräfta att alla interaktiva element har hover-effekter eller visuella indikationer på interaktivitet.
        Testa dark/light mode (om tillgängligt) för att se till att alla element visas tydligt i båda lägena.

    Förväntat resultat:
        Alla gränssnittselement är korrekt placerade och visas enligt design.
        Alla knappar och länkar fungerar som förväntat och leder till rätt sektioner.
        Responsiv design fungerar som förväntat och alla element anpassas korrekt för olika enheter.
        Dark/light mode byter färgschema korrekt och påverkar inte läsbarheten eller funktionaliteten.

    Utfallsstatus: Pass/Fail
